growth2/app/Http/routes.php
<?php

Route::get('/', function () {
   return view('welcome');
    //return redirect('admin/dashboard');
});

//Login Admin
Route::get('/admin',array('as' => 'admin.login','uses' => 'AdminController@getLogin'));
Route::post('/admin', array('as' => 'admin.auth.login','uses' => 'AdminController@postLogin'));

//Login Manager
Route::get('/manager',array('as' => 'manager.login','uses' => 'ManagerController@getLogin'));
Route::post('/manager', array('as' => 'manager.auth.login','uses' => 'ManagerController@postLogin'));

//Reset Password
Route::get('/resetpassword',array('as' => 'admin.autentikasi','uses' => 'AdminController@autentikasi'));
Route::post('/resetpassword/auth',array('as' => 'admin.reset.password','uses' => 'AdminController@sendEmailReminder'));

//REST API 
Route::group(array('prefix'=>'api'),function(){
	Route::resource('webService','WebServiceController',array('except'=>array('create','edit')));
});

//Register
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');

        //AJAX
		Route::get('/ajax-call', function(){
		    $id = Input::get('kd_outlet');
		    $user = \App\Outlet::where('kd_outlet', '=', $id)
		    ->join('user','outlet.kd_user','=','user.id')
		    ->get();
		    return Response::json($user);
		});

		Route::get('/ajax-city', function(){
		    $id = Input::get('id');
		    $city = \App\Kota::where('kd_area','=',$id)
		    ->get();
		    
		    return Response::json($city);
		});

		Route::get('/ajax-area', function(){
		    $id = Input::get('id');
		    $area = \App\Area::where('id','=',$id)
		    ->get();
		    return Response::json($area);
		});

                Route::get('/ajax-sales', function(){
		    $id = Input::get('id');
		    $area = \App\User::where('kd_area','=',$id)
		    ->where('kd_role','=','3')
		    ->get();
		    return Response::json($area);
		});


Route::group(['middlewareGroups' => ['web']], function () {
    Route::group(['middleware' => ['auth','admin','acl']], function()
	{
		//Dashboard
		Route::get('/admin/dashboard', array('as' => 'admin.dashboard','uses' =>'AdminController@getDashboard'));

		//ChangesPassword
		Route::get('/admin/changepassword',array('as' => 'admin.getChangePassword', 'uses' => 'AdminController@getChangePassword'));
		Route::post('/admin/changepassword',array('as' => 'admin.postChangePassword', 'uses' => 'AdminController@postChangePassword'));

		//Logout
		Route::get('admin/logout',array('as' => 'admin.logout','uses' =>'AdminController@getLogout'));

		//Sales Force
		Route::get('/admin/sales/{id}/delete',array('as'=> 'admin.sales.delete','uses' => 'SalesController@destroy'));
		Route::resource('/admin/sales', 'SalesController');

		//User
		Route::get('/admin/user/{id}/delete',array('as'=> 'admin.user.delete','uses' => 'UserController@destroy'));
		Route::resource('/admin/user', 'UserController');

		//Area
		Route::get('/admin/area/{id}/delete',array('as'=> 'admin.area.delete','uses' => 'AreaController@destroy'));
		Route::resource('/admin/area', 'AreaController');

		//Kota
		Route::get('/admin/kota/{id}/delete',array('as'=> 'admin.kota.delete','uses' => 'KotaController@destroy'));
		Route::resource('/admin/kota', 'KotaController');

		//Produk
		Route::get('/admin/produk/{id}/delete',array('as'=> 'admin.produk.delete','uses' => 'ProdukController@destroy'));
		Route::resource('/admin/produk', 'ProdukController');

		//Distributor
		Route::get('/admin/distributor/{id}/delete',array('as'=> 'admin.distributor.delete','uses' => 'DistributorController@destroy'));
		Route::resource('/admin/distributor', 'DistributorController');

		//Outlet
		Route::get('/admin/outlet/{kd_outlet}/delete',array('as'=> 'admin.outlet.delete','uses' => 'OutletController@destroy'));
		Route::resource('/admin/outlet', 'OutletController'); 

        //Toleransi Koordinat
        Route::get('admin/outletManage', array('as' => 'admin.outletManage.index','uses' => 'OutletController@formToleransi'));
		Route::post('admin/outletManage', array('as' => 'admin.outletManage.updateToleransi','uses' => 'OutletController@updateToleransi'));
   
        //Tipe Outlet
		Route::get('/admin/tipe/{id}/delete',array('as'=> 'admin.tipe.delete','uses' => 'TipeOutletController@destroy'));
		Route::resource('/admin/tipe', 'TipeOutletController'); 

        //Visit Plan Get data
		Route::get('admin/visitPlan', array('as' => 'admin.visitPlan.form', 'uses' => 'VisitPlanController@formVisit'));
		Route::post('admin/VisitPlan', array('as' => 'admin.visitPlan.result','uses' => 'VisitPlanController@index'));	
 
        //Approval Checklist
		Route::get('/admin/visit/approved',array('as'=> 'admin.visit.editApprove','uses' => 'VisitPlanController@editApprove'));
		Route::post('/admin/visit/approved',array('as'=> 'admin.visit.approved','uses' => 'VisitPlanController@approvedVisit'));

        //Visit Monitor Get data
		Route::get('admin/visitingMonitor', array('as' => 'admin.visitingMonitor.form', 'uses' => 'VisitMonitorController@formVisit'));
		Route::post('admin/visitingMonitor', array('as' => 'admin.visitingMonitor.result','uses' => 'VisitMonitorController@index'));	
                
        //Visit Plan
		Route::get('/admin/visit/{id}/delete',array('as'=> 'admin.visit.delete','uses' => 'VisitPlanController@destroy'));
		Route::resource('/admin/visit', 'VisitPlanController');
	
        //Visiting Monitor
		Route::get('/admin/visitMonitor/{id}/delete',array('as'=> 'admin.visitMonitor.delete','uses' => 'VisitMonitorController@destroy'));
		Route::resource('/admin/visitMonitor', 'VisitMonitorController');

        //Take Order Get data
		Route::get('admin/takeOrder', array('as' => 'admin.takeOrder.form', 'uses' => 'OrderController@formOrder'));
		Route::post('admin/takeOrder', array('as' => 'admin.takeOrder.result','uses' => 'OrderController@index'));	

		//Take Order
		Route::get('/admin/order/{id}/delete',array('as'=> 'admin.order.delete','uses' => 'OrderController@destroy'));
		Route::resource('/admin/order', 'OrderController');
                
        //Photo Activity Get data
		Route::get('admin/photoAct', array('as' => 'admin.photoAct.form', 'uses' => 'PhotoActivityController@formPhoto'));
		Route::post('admin/photoAct', array('as' => 'admin.photoAct.result','uses' =>'PhotoActivityController@index'));	               
	        
        //Photo Display
		Route::get('/admin/photo/{id}/delete',array('as'=> 'admin.photo.delete','uses' => 'PhotoActivityController@destroy'));
		Route::resource('/admin/photo', 'PhotoActivityController');
     
        //Tipe Photo
		Route::get('/admin/tipephoto/{id}/delete',array('as'=> 'admin.tipephoto.delete','uses' => 'TipePhotoController@destroy'));
		Route::resource('/admin/tipephoto', 'TipePhotoController');

		//Competitor Activity
		Route::get('/admin/competitor/{id}/delete',array('as'=> 'admin.competitor.delete','uses' => 'CompetitorActivityController@destroy'));
		Route::resource('/admin/competitor', 'CompetitorActivityController');

        //Competitor
		Route::get('/admin/comp/{id}/delete',array('as'=> 'admin.comp.delete','uses' => 'CompetitorController@destroy'));
		Route::resource('/admin/comp', 'CompetitorController');

		//Report
		Route::get('admin/report/', array('as' => 'admin.report', 'uses' => 'ReportController@getReport'));

        //Report Outlet Visit per sales
		Route::get('admin/report/outletVisit', array('as' => 'admin.report.outletVisit', 'uses' => 'ReportController@outletVisit'));
		Route::post('admin/report/outletVisit', array('as' => 'admin.report.resultReport','uses' => 'ReportController@resultReport'));

        //Report Working Time per sales
		Route::get('admin/report/workingTime', array('as' => 'admin.report.workingTime', 'uses' => 'ReportController@workingTime'));
		Route::post('admin/report/workingTime', array('as' => 'admin.report.resultWorkTime','uses' => 'ReportController@resultWorkTime'));

		//Report Effective Call per sales
		Route::get('admin/report/effectiveCall', array('as' => 'admin.report.effectiveCall', 'uses' => 'ReportController@effectiveCall'));
		Route::post('admin/report/effectiveCall', array('as' => 'admin.report.resultEffectiveCall', 'uses' => 'ReportController@resultEffectiveCall'));

        //Report Photo Activity per sales
		Route::get('admin/report/photoActivity', array('as' => 'admin.report.photoActivity', 'uses' => 'ReportController@photoActivity'));
		Route::post('admin/report/photoActivity', array('as' => 'admin.report.resultPhotoActivity', 'uses' => 'ReportController@resultPhotoActivity'));
		Route::get('admin/download/reportPhoto',array('as' => 'admin.reportPhoto.download','uses' =>'ReportController@exportAllPhoto'));
		//Report Competitor Photo Activity per sales
		Route::get('admin/report/competitorActivity', array('as' => 'admin.report.competitorActivity', 'uses' => 'ReportController@competitorActivity'));
		Route::post('admin/report/competitorActivity', array('as' => 'admin.report.resultCompetitorActivity', 'uses' => 'ReportController@resultCompetitorActivity'));
		//Route::get('admin/download/reportPhoto',array('as' => 'admin.reportPhoto.download','uses' =>'ReportController@exportAllPhoto'));
		//Configuration
		Route::get('/admin/permission/{id}/delete',array('as'=> 'admin.permission.delete','uses' => 'PermissionRoleController@destroy'));
		Route::resource('/admin/permission', 'PermissionController');

		Route::get('/admin/role/{id}/delete',array('as'=> 'admin.role.delete','uses' => 'RoleController@destroy'));
		Route::resource('/admin/role', 'RoleController');

        Route::get('/admin/adminmenu/{id}/delete',array('as'=> 'admin.adminmenu.delete','uses' => 'AdminMenuController@destroy'));
		Route::resource('/admin/adminmenu', 'AdminMenuController');

		//Download
		Route::get('admin/download',array('as' => 'admin.download','uses' =>'DownloadController@index'));
		Route::get('admin/download/area',array('as' => 'admin.download.area','uses' =>'DownloadController@exportArea'));

growth2/app/Role.php
<?php

namespace App;
use Illuminate\Database\Eloquent\Model;
use App\User;
use App\Permission;

class Role extends Model
{
    //
    protected $table = 'role';
    protected $guarded = ['kd_role'];
    protected $primaryKey = 'kd_role';
    public $timestamps = false;

    public function users()
    {
    	return $this->hasMany('App\User', 'kd_role', 'kd_role');
    }

    public function permission()
    {
        return $this->belongsToMany('App\Permission', 'permission_role', 'kd_role', 'kd_permission');
    }

    public function adminmenu()
    {
        return $this->belongsToMany('App\AdminMenu', 'admin_menu_role', 'kd_role', 'kd_admin_menu');
    }
 
    //Untuk Delete
    public function permissions()
    {
        return $this->hasMany('App\PermissionRole', 'kd_role', 'kd_role');
    }

    public function adminmenus()
    {
        return $this->hasMany('App\AdminMenuRole',  'kd_role', 'kd_role');
    }
}

growth2/app/Http/Controllers/RoleController.php
<?php 
/*
    PT. Trikarya Teknologi Indonesia
    Tenggilis raya 127
    Office Complex Apartment Metropolis MKB 206
    Surabaya, Jawa timur, Indonesia
    Phone : +6231-8420384 / +6281235537717
    Code By : Novita Nata Wardanie
*/
namespace App\Http\Controllers;
use DB;
use Input;
use Session;
use App\Role;
use App\Permission;
use App\AdminMenu;
use App\PermissionRole;
use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Requests\AdminRoleRequest;
use App\Http\Requests\RoleRequest;
use App\Http\Controllers\Controller;
use App\Http\Controllers\AdminController;

class RoleController extends Controller {

	public function index()
	{
		$data = Role::all();
		return view('pages.role.index', compact('data'));
	}

	public function create()
	{
		return view('pages.role.create');
	}

	public function store(RoleRequest $request)
	{
		Role::create($request->all());
                $log = new AdminController;
	        $log->getLogHistory('Make New Role');
	    Session::flash('create', 'Role baru berhasil ditambahkan');
		return redirect()->route('admin.role.index');
	}

	public function edit($kd_role)
	{
		$data['adminmenu'] = Adminmenu::lists('nm_menu','id');
		$data['permission'] = Permission::lists('nm_permission','id');
		$data['content'] = Role::with('permission')->find($kd_role);
		$data['permission_t'] = $data['content']->permission->lists('id')->toArray();
		$data['adminmenu_t'] = $data['content']->adminmenu->lists('id')->toArray();
		return view('pages.role.edit', compact('data'));
		//dd($data['adminmenu_t']);
	}

	public function update(RoleRequest $request, $kd_role)
	{
		$data = Role::find($kd_role);
		$data->type_role = $request->input('type_role');
		$data->save();
		$data->adminmenu()->detach();
		if(is_array($request->input('adminmenu')))
		{
			foreach ($request->input('adminmenu') as $row) {
				$data->adminmenu()->attach($row);
			}
		}
		$data->permission()->detach();
		if(is_array($request->input('permission')))
		{
			foreach ($request->input('permission') as $row) {
				$data->permission()->attach($row);
			}
		}
                $log = new AdminController;
	        $log->getLogHistory('Update Role with ID '.$kd_role);
	    Session::flash('update', 'Role berhasil diperbaharui');
		return redirect()->route('admin.role.index');
	}

	public function destroy($kd_role)
	{
        $data = Role::with(
        'permissions',
        'adminmenus'  
         )->find($kd_role);
         foreach ($data->permissions as $row) {
    	$row->delete();
         }
         foreach ($data->adminmenus as $row) {
		$row->delete();
         }
        $data->delete();
        $log = new AdminController;
	    $log->getLogHistory('Delete Role with ID '.$kd_role);
	    Session::flash('delete', 'Role berhasil dihapus');
	    return redirect()->route('admin.role.index');
	}

}

growth2/resources/views/pages/role/create.blade.php
@extends('layouts.master')

@section('title', 'Create Role')

@section('content')

        <!-- Main Content -->
        <div class="page-wrapper">
            <div class="container-fluid">
                
                <!-- Title -->
                <div class="row heading-bg">
                    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                        <h5 class="txt-dark">Role management</h5>
                    </div>
                    <!-- Breadcrumb -->
                    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                        <ol class="breadcrumb">
                            <li><a href="{{url('/admin/dashboard')}}"><i class="fa fa-home"></i>&nbsp;Home</a></li>
                            <li><a href="#"><span>Configuration</span></a></li>
                            <li><a href="{{url('/admin/role')}}"><span>Role</span></a></li>
                            <li class="active"><span>Add Role</span></li>
                        </ol>
                    </div>
                    <!-- /Breadcrumb -->
                </div>
                <!-- /Title -->

                <!-- Row -->
                    <div class="row">
                        <div class="col-md-12">
                            <div class="panel panel-primary card-view">
                                <div class="panel-heading">
                                    <div class="pull-left">
                                        <h6 class="panel-title txt-light"><i class="fa fa-wpforms"></i>&nbsp;&nbsp;Form Add Role</h6>
                                    </div>
                                    @include('partials.panel')
                                    <div class="clearfix"></div>
                                </div>
                                <div id="collapse_1" class="panel-wrapper collapse in">
                                    <div class="panel-body">
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-wrap">

                                                    {!! Form::open(array('route' => 'admin.role.store', 'method' => 'POST', 'data-toggle' => 'validator', 'role' => 'form')) !!}
                                                        @include('pages.role.form',array('submit' => 'Simpan'))
                                                    {!! Form::close() !!}

                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                <!-- /Row -->

                @include('partials.footer')

            </div>
        </div>
        <!-- /Main Content -->

@endsection

growth2/resources/views/pages/role/edit.blade.php
@extends('layouts.master')

@section('title', 'Edit Role')

@section('content')

        <!-- Main Content -->
        <div class="page-wrapper">
            <div class="container-fluid">
                
                <!-- Title -->
                <div class="row heading-bg">
                    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                        <h5 class="txt-dark">Role management</h5>
                    </div>
                    <!-- Breadcrumb -->
                    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                        <ol class="breadcrumb">
                            <li><a href="{{url('/admin/dashboard')}}"><i class="fa fa-home"></i>&nbsp;Home</a></li>
                            <li><a href="#"><span>Configuration</span></a></li>
                            <li><a href="{{url('/admin/role')}}"><span>Role</span></a></li>
                            <li class="active"><span>Edit Role</span></li>
                        </ol>
                    </div>
                    <!-- /Breadcrumb -->
                </div>
                <!-- /Title -->

                <!-- Row -->
                <div class="row">
                    <div class="col-sm-12">
                        <div class="panel panel-primary card-view">
                            <div class="panel-heading">
                                <div class="pull-left">
                                    <h6 class="panel-title txt-light"><i class="fa fa-wpforms"></i>&nbsp;&nbsp;Edit Role</h6>
                                </div>
                                @include('partials.panel')
                                <div class="clearfix"></div>
                            </div>
                            <div id="collapse_1" class="panel-wrapper collapse in">
                                <div class="panel-body">

                                    {!! Form::model($data['content'], array('route' => ['admin.role.update',$data['content']->kd_role], 'method' => 'PUT')) !!}

                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-wrap">
                                                <div class="col-md-3">
                                                    <div class="form-group">

                                                        {!! Form::label('type_role','Nama Role', array('class' => 'control-label mb-10')) !!}
                                                        {!! Form::text('type_role',null, array('class' => 'form-control')) !!}
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row pa-15">
                                        <h3><center>Admin Menu</center></h3>
                                        @foreach($data['adminmenu'] as $key => $value)
                                            <div class="icon-container col-sm-6 col-md-4 col-lg-3 pa-5 pl-20">
                                                <div class="checkbox checkbox-primary ">
                                                    <input id="checkbox2" type="checkbox" id="menuadmin" name="adminmenu[]" value="{{ $key }}" {{ in_array($key, $data['adminmenu_t'])?'checked':'' }} > 
                                                    <label for="checkbox2">&nbsp;{!! $value !!}</label>
                                                </div>
                                            </div>
                                        @endforeach
                                    </div>

                                    <div class="row pa-10">
                                        <h3><center>Permission</center></h3>
                                        @foreach($data['permission'] as $key => $value)
                                            <div class="icon-container col-sm-6 col-md-4 col-lg-3 pa-5 pl-20">
                                                <div class="checkbox checkbox-primary ">
                                                    <input id="checkbox2" type="checkbox" id="routeadmin" name="permission[]" value="{{ $key }}" {{ in_array($key, $data['permission_t'])?'checked':'' }} > 
                                                    <label for="checkbox2">&nbsp;{!! $value !!}</label>
                                                </div>
                                            </div>
                                        @endforeach
                                    </div>

                                    <div class="row pa-30 pb-0">
                                        <center>
                                            <input type="button" id="check" class="btn btn-primary" value="Check All" />
                                            <input type="button" id="uncheck" class="btn btn-primary" value="UnCheck All" />
                                        </center>
                                    </div>

                                    <div class="row pa-10">
                                        <center>
                                            {!! Form::submit('Perbarui', array('class' => 'btn btn-success')) !!}
                                        </center>
                                    </div>

                                </div>
                                  
                                {!! Form::close() !!}

                            </div>
                        </div>
                    </div>
                </div>
                <!-- /Row -->

                @include('partials.footer')

            </div>
        </div>
        <!-- /Main Content -->

         <script>
            $(document).ready( function() {
                $('#check').on('click', function () {
                    var allInputs = document.getElementsByTagName("input");
                    for (var i = 0, max = allInputs.length; i < max; i++){
                        if (allInputs[i].type === 'checkbox')
                            allInputs[i].checked = true;
                    }
                });
                $('#uncheck').on('click', function () {
                    var allInputs = document.getElementsByTagName("input");
                    for (var i = 0, max = allInputs.length; i < max; i++){
                        if (allInputs[i].type === 'checkbox')
                            allInputs[i].checked = false;
                    }
                });
            });
        </script>

@endsection


       

growth2/resources/views/pages/role/form.blade.php
<div class="col-xs-6 col-sm-4 col-sm-offset-4">
	<div class="form-group">
	    {!! Form::label('type_role','Nama Role', array('class' => 'control-label mb-10')) !!}
		{!! Form::text('type_role',null, array('class' => 'form-control', 'required')) !!}
	</div>
    <div class="form-group">
        {!! Form::submit('Simpan', array('class' => 'btn btn-primary')) !!}
    </div>
</div>

growth2/resources/views/pages/role/index.blade.php
@extends('layouts.master')

@section('title', 'Role List')

@section('content')

        <!-- Main Content -->
        <div class="page-wrapper">
            <div class="container-fluid">
                
                <!-- Title -->
                <div class="row heading-bg">
                    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                        <h5 class="txt-dark">Role management</h5>
                    </div>
                    <!-- Breadcrumb -->
                    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                        <ol class="breadcrumb">
                            <li><a href="{{url('/admin/dashboard')}}"><i class="fa fa-home"></i>&nbsp;Home</a></li>
                            <li><a href="#"><span>Configuration</span></a></li>
                            <li class="active"><span>Role</span></li>
                        </ol>
                    </div>
                    <!-- /Breadcrumb -->
                </div>
                <!-- /Title -->

                <!-- Row -->
                <div class="row">
                    <div class="col-sm-12">
                        <div class="panel panel-primary card-view">
                            <div class="panel-heading">
                                <div class="pull-left">
                                    <h6 class="panel-title txt-light"><i class="fa fa-lock"></i>&nbsp;&nbsp;Role List</h6>
                                </div>
                                @include('partials.panel')
                                <div class="clearfix"></div>
                            </div>
                            <div id="collapse_1" class="panel-wrapper collapse in">
                                <div class="panel-body">
                                    <div class="table-wrap">
                                        
                                        <a href="{!! route('admin.role.create') !!}" class="btn btn-primary"><i class="fa fa-plus">&nbsp;&nbsp;Tambah Role</i></a>
                                      

                                        <div class="table-responsive">
                                            <table class="table datable_1 table-hover table-bordered display mb-30">
                                                <thead>
                                                    <tr>
                                                        <th>#</th>
                                                        <th>Role</th>
                                                        @if(Auth::user()->kd_role != 3) 
                                                            <th>Action</th>
                                                        @else
                                                            <th></th>
                                                        @endif
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    @foreach($data as $row)
                                                        <tr>
                                                            <td>{{ $row->kd_role }}</td>
                                                            <td>{{ $row->type_role }}</td>  
                                                            @if(Auth::user()->kd_role != 3)   
                                                                <td>
                                                                    <center>
                                                                        <div class="button-list">
                                                                            <a href="{!! route('admin.role.edit',[$row->kd_role]) !!}" data-toggle="tooltip" title="Edit" class="btn btn-success btn-sm btn-icon-anim btn-square mr-5" style="display: unset;"><i class="fa fa-pencil" style="font-size: 14px;"></i></a>    
                                                                            <a href="{!! route('admin.role.delete',[$row->kd_role]) !!}" id="delete" data-toggle="tooltip" title="Delete" class="btn btn-danger btn-sm btn-icon-anim btn-square mr-5" style="display: unset;"><i class="fa fa-trash" style="font-size: 14px;"></i></a>
                                                                        </div>
                                                                    </center>      
                                                                </td>
                                                            @endif
                                                        </tr>
                                                    @endforeach
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>  
                    </div>
                </div>
                <!-- /Row -->
            
                @include('partials.footer')

            </div>
        </div>
        <!-- /Main Content -->

        @include('partials.sweetalert')

        @push('message')
            @include('partials.toastr')
        @endpush

@endsection