growth2/app/Http/routes.php
		    return Response::json($area);
		});

                Route::get('/ajax-sales', function(){
		    $id = Input::get('id');
		    $area = \App\User::where('kd_area','=',$id)
		    ->where('kd_role','=','3')
		    ->get();
		    return Response::json($area);
		});


Route::group(['middlewareGroups' => ['web']], function () {
    Route::group(['middleware' => ['auth','admin','acl']], function()
	{
		//Dashboard
		Route::get('/admin/dashboard', array('as' => 'admin.dashboard','uses' =>'AdminController@getDashboard'));

		//ChangesPassword
		Route::get('/admin/changepassword',array('as' => 'admin.getChangePassword', 'uses' => 'AdminController@getChangePassword'));
		Route::post('/admin/changepassword',array('as' => 'admin.postChangePassword', 'uses' => 'AdminController@postChangePassword'));

		//Logout
		Route::get('admin/logout',array('as' => 'admin.logout','uses' =>'AdminController@getLogout'));

		//Sales Force
		Route::get('/admin/sales/{id}/delete',array('as'=> 'admin.sales.delete','uses' => 'SalesController@destroy'));
		Route::resource('/admin/sales', 'SalesController');

		//User
		Route::get('/admin/user/{id}/delete',array('as'=> 'admin.user.delete','uses' => 'UserController@destroy'));
		Route::resource('/admin/user', 'UserController');

		//Area
		Route::get('/admin/area/{id}/delete',array('as'=> 'admin.area.delete','uses' => 'AreaController@destroy'));
		Route::resource('/admin/area', 'AreaController');

		//Kota
		Route::get('/admin/kota/{id}/delete',array('as'=> 'admin.kota.delete','uses' => 'KotaController@destroy'));
		Route::resource('/admin/kota', 'KotaController');

		//Produk
		Route::get('/admin/produk/{id}/delete',array('as'=> 'admin.produk.delete','uses' => 'ProdukController@destroy'));
		Route::resource('/admin/produk', 'ProdukController');

		//Distributor
		Route::get('/admin/distributor/{id}/delete',array('as'=> 'admin.distributor.delete','uses' => 'DistributorController@destroy'));
		Route::resource('/admin/distributor', 'DistributorController');

		//Outlet
		Route::get('/admin/outlet/{kd_outlet}/delete',array('as'=> 'admin.outlet.delete','uses' => 'OutletController@destroy'));
		Route::resource('/admin/outlet', 'OutletController'); 

        //Toleransi Koordinat
        Route::get('admin/outletManage', array('as' => 'admin.outletManage.index','uses' => 'OutletController@formToleransi'));
		Route::post('admin/outletManage', array('as' => 'admin.outletManage.updateToleransi','uses' => 'OutletController@updateToleransi'));
   
        //Tipe Outlet
		Route::get('/admin/tipe/{id}/delete',array('as'=> 'admin.tipe.delete','uses' => 'TipeOutletController@destroy'));
		Route::resource('/admin/tipe', 'TipeOutletController'); 

        //Visit Plan Get data
		Route::get('admin/visitPlan', array('as' => 'admin.visitPlan.form', 'uses' => 'VisitPlanController@formVisit'));
		Route::post('admin/VisitPlan', array('as' => 'admin.visitPlan.result','uses' => 'VisitPlanController@index'));	
 
        //Approval Checklist
		Route::get('/admin/visit/approved',array('as'=> 'admin.visit.editApprove','uses' => 'VisitPlanController@editApprove'));
		Route::post('/admin/visit/approved',array('as'=> 'admin.visit.approved','uses' => 'VisitPlanController@approvedVisit'));

        //Visit Monitor Get data
		Route::get('admin/visitingMonitor', array('as' => 'admin.visitingMonitor.form', 'uses' => 'VisitMonitorController@formVisit'));
		Route::post('admin/visitingMonitor', array('as' => 'admin.visitingMonitor.result','uses' => 'VisitMonitorController@index'));	
                
        //Visit Plan
		Route::get('/admin/visit/{id}/delete',array('as'=> 'admin.visit.delete','uses' => 'VisitPlanController@destroy'));
		Route::resource('/admin/visit', 'VisitPlanController');
	
        //Visiting Monitor
		Route::get('/admin/visitMonitor/{id}/delete',array('as'=> 'admin.visitMonitor.delete','uses' => 'VisitMonitorController@destroy'));
		Route::resource('/admin/visitMonitor', 'VisitMonitorController');

        //Take Order Get data
		Route::get('admin/takeOrder', array('as' => 'admin.takeOrder.form', 'uses' => 'OrderController@formOrder'));
		Route::post('admin/takeOrder', array('as' => 'admin.takeOrder.result','uses' => 'OrderController@index'));	

		//Take Order
		Route::get('/admin/order/{id}/delete',array('as'=> 'admin.order.delete','uses' => 'OrderController@destroy'));
		Route::resource('/admin/order', 'OrderController');
                
        //Photo Activity Get data
		Route::get('admin/photoAct', array('as' => 'admin.photoAct.form', 'uses' => 'PhotoActivityController@formPhoto'));
		Route::post('admin/photoAct', array('as' => 'admin.photoAct.result','uses' =>'PhotoActivityController@index'));	               
	        
        //Photo Display
		Route::get('/admin/photo/{id}/delete',array('as'=> 'admin.photo.delete','uses' => 'PhotoActivityController@destroy'));
		Route::resource('/admin/photo', 'PhotoActivityController');
     
        //Tipe Photo
		Route::get('/admin/tipephoto/{id}/delete',array('as'=> 'admin.tipephoto.delete','uses' => 'TipePhotoController@destroy'));
		Route::resource('/admin/tipephoto', 'TipePhotoController');

		//Competitor Activity
		Route::get('/admin/competitor/{id}/delete',array('as'=> 'admin.competitor.delete','uses' => 'CompetitorActivityController@destroy'));
		Route::resource('/admin/competitor', 'CompetitorActivityController');

        //Competitor
		Route::get('/admin/comp/{id}/delete',array('as'=> 'admin.comp.delete','uses' => 'CompetitorController@destroy'));
		Route::resource('/admin/comp', 'CompetitorController');

		//Report
		Route::get('admin/report/', array('as' => 'admin.report', 'uses' => 'ReportController@getReport'));

        //Report Outlet Visit per sales
		Route::get('admin/report/outletVisit', array('as' => 'admin.report.outletVisit', 'uses' => 'ReportController@outletVisit'));
		Route::post('admin/report/outletVisit', array('as' => 'admin.report.resultReport','uses' => 'ReportController@resultReport'));

        //Report Working Time per sales
		Route::get('admin/report/workingTime', array('as' => 'admin.report.workingTime', 'uses' => 'ReportController@workingTime'));
		Route::post('admin/report/workingTime', array('as' => 'admin.report.resultWorkTime','uses' => 'ReportController@resultWorkTime'));

		//Report Effective Call per sales
		Route::get('admin/report/effectiveCall', array('as' => 'admin.report.effectiveCall', 'uses' => 'ReportController@effectiveCall'));
		Route::post('admin/report/effectiveCall', array('as' => 'admin.report.resultEffectiveCall', 'uses' => 'ReportController@resultEffectiveCall'));

        //Report Photo Activity per sales
		Route::get('admin/report/photoActivity', array('as' => 'admin.report.photoActivity', 'uses' => 'ReportController@photoActivity'));
		Route::post('admin/report/photoActivity', array('as' => 'admin.report.resultPhotoActivity', 'uses' => 'ReportController@resultPhotoActivity'));
		Route::get('admin/download/reportPhoto',array('as' => 'admin.reportPhoto.download','uses' =>'ReportController@exportAllPhoto'));
		//Report Competitor Photo Activity per sales
		Route::get('admin/report/competitorActivity', array('as' => 'admin.report.competitorActivity', 'uses' => 'ReportController@competitorActivity'));
		Route::post('admin/report/competitorActivity', array('as' => 'admin.report.resultCompetitorActivity', 'uses' => 'ReportController@resultCompetitorActivity'));
		//Route::get('admin/download/reportPhoto',array('as' => 'admin.reportPhoto.download','uses' =>'ReportController@exportAllPhoto'));
		//Configuration
		Route::get('/admin/permission/{id}/delete',array('as'=> 'admin.permission.delete','uses' => 'PermissionRoleController@destroy'));
		Route::resource('/admin/permission', 'PermissionController');

		Route::get('/admin/role/{id}/delete',array('as'=> 'admin.role.delete','uses' => 'RoleController@destroy'));
		Route::resource('/admin/role', 'RoleController');

        Route::get('/admin/adminmenu/{id}/delete',array('as'=> 'admin.adminmenu.delete','uses' => 'AdminMenuController@destroy'));
		Route::resource('/admin/adminmenu', 'AdminMenuController');

		//Download
		Route::get('admin/download',array('as' => 'admin.download','uses' =>'DownloadController@index'));
		Route::get('admin/download/area',array('as' => 'admin.download.area','uses' =>'DownloadController@exportArea'));
		Route::get('admin/download/outlet',array('as' => 'admin.download.outlet','uses' =>'DownloadController@exportOutlet'));
		Route::get('admin/download/distributor',array('as' => 'admin.download.distributor','uses' =>'DownloadController@exportDistributor'));
		Route::get('admin/download/produk',array('as' => 'admin.download.produk','uses' =>'DownloadController@exportProduk'));
		Route::get('admin/download/visitPlan',array('as' => 'admin.download.visitPlan','uses' =>'DownloadController@exportVisitPlan'));
		Route::get('admin/download/visitMonitor',array('as' => 'admin.download.visitMonitor','uses' =>'DownloadController@exportVisitMonitor'));
		Route::get('admin/download/takeOrder',array('as' => 'admin.download.takeOrder','uses' =>'DownloadController@exportTakeOrder'));
		Route::get('admin/download/salesForce',array('as' => 'admin.download.salesForce','uses' =>'DownloadController@exportSalesForce'));
		Route::get('admin/download/nonSF',array('as' => 'admin.download.nonSF','uses' =>'DownloadController@exportNonSF'));
		Route::get('admin/download/salesDetail/{id}',array('as' => 'admin.download.salesDetail','uses' =>'DownloadController@exportSalesDetail'));
		
		//Upload
		Route::post('admin/upload/outlet',array('as' => 'admin.upload.outlet','uses' =>'DownloadController@uploadOutlet'));
		Route::post('admin/upload/produk',array('as' => 'admin.upload.produk','uses' =>'DownloadController@uploadProduk'));
		Route::post('admin/upload/distributor',array('as' => 'admin.upload.distributor','uses' =>'DownloadController@uploadDistributor'));
		Route::post('admin/upload/area',array('as' => 'admin.upload.area','uses' =>'DownloadController@uploadArea'));

growth2/resources/views/pages/visitMonitor/create.blade.php
@extends('layouts.master')

@section('link', '
    <link href="/doodle/vendors/bower_components/mjolnic-bootstrap-colorpicker/dist/css/bootstrap-colorpicker.min.css" rel="stylesheet" type="text/css"/>
  <link href="/doodle/vendors/bower_components/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css" rel="stylesheet" type="text/css"/>')

@section('title', 'Create Visit Plan')

@section('content')

        <!-- Main Content -->
        <div class="page-wrapper">
            <div class="container-fluid">
                
                <!-- Title -->
                <div class="row heading-bg">
                    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                        <h5 class="txt-dark">Visit Plant management</h5>
                    </div>
                    <!-- Breadcrumb -->
                    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                        <ol class="breadcrumb">
                            <li><a href="{{url('/admin/dashboard')}}"><i class="fa fa-home"></i>&nbsp;Home</a></li>
                            <li><a href="#"><span>Master Data</span></a></li>
                            <li><a href="{{url('/admin/visit')}}"><span>Visit Plan</span></a></li>
                            <li class="active"><span>Add Visit Plan</span></li>
                        </ol>
                    </div>
                    <!-- /Breadcrumb -->
                </div>
                <!-- /Title -->

                <!-- Row -->
                    <div class="row">
                        <div class="col-md-12">
                            <div class="panel panel-primary card-view">
                                <div class="panel-heading">
                                    <div class="pull-left">
                                        <h6 class="panel-title txt-light"><i class="fa fa-wpforms">Form Add Visit Plan</h6>
                                    </div>
                                    @include('partials.panel')
                                    <div class="clearfix"></div>
                                </div>
                                <div id="collapse_1" class="panel-wrapper collapse in">
                                    <div class="panel-body">
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-wrap">

                                                    {!! Form::open(array('route' => 'admin.visit.store', 'method' => 'POST', 'data-toggle' => 'validator', 'role' => 'form')) !!}
                                                      @include('pages.visit.form',array('submit' => 'Simpan'))
                                                    {!! Form::close() !!}

                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                <!-- /Row -->

                @include('partials.footer')

            </div>
        </div>
        <!-- /Main Content -->

@endsection

growth2/resources/views/pages/visitMonitor/edit.blade.php
@extends('layouts.master')

@section('link', '
    <link href="/doodle/vendors/bower_components/mjolnic-bootstrap-colorpicker/dist/css/bootstrap-colorpicker.min.css" rel="stylesheet" type="text/css"/>
  <link href="/doodle/vendors/bower_components/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css" rel="stylesheet" type="text/css"/>')

@section('title', 'Edit Visiting Monitor')

@section('content')

        <!-- Main Content -->
        <div class="page-wrapper">
            <div class="container-fluid">
                
                <!-- Title -->
                <div class="row heading-bg">
                    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                        <h5 class="txt-dark">Visiting Monitor management</h5>
                    </div>
                    <!-- Breadcrumb -->
                    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                        <ol class="breadcrumb">
                            <li><a href="{{url('/admin/dashboard')}}"><i class="fa fa-home"></i>&nbsp;Home</a></li>
                            <li><a href="#"><span>Master Data</span></a></li>
                            <li><a href="{{url('/admin/visitingMonitor')}}"><span>Visiting Monitor</span></a></li>
                            <li class="active"><span>Edit Visiting Monitor</span></li>
                        </ol>
                    </div>
                    <!-- /Breadcrumb -->
                </div>
                <!-- /Title -->

                <!-- Row -->
                    <div class="row">
                        <div class="col-md-12">
                            <div class="panel panel-primary card-view">
                                <div class="panel-heading">
                                    <div class="pull-left">
                                        <h6 class="panel-title txt-light">Form Edit Visiting Monitor</h6>
                                    </div>
                                    @include('partials.panel')
                                    <div class="clearfix"></div>
                                </div>
                                <div id="collapse_1" class="panel-wrapper collapse in">
                                    <div class="panel-body">
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-wrap">

                                                    {!! Form::model($data['content'],array('route' => ['admin.visitMonitor.update',$data['content']->id], 'method' => 'PUT', 'data-toggle' => 'validator', 'role' => 'form')) !!}
                                                        @include('pages.visitMonitor.form',array('submit' => 'Perbarui'))
                                                    {!! Form::close() !!}

                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                <!-- /Row -->

                @include('partials.footer')

            </div>
        </div>
        <!-- /Main Content -->

@endsection

growth2/resources/views/pages/visitMonitor/form.blade.php
<div class="col-xs-6 col-sm-4 col-sm-offset-4">
	<div class="form-group">
		{!! Form::label('kd_outlet','Nama Outlet', array('class' => 'control-label mb-10')) !!}
		{!! Form::select('kd_outlet', $outlet, null, array('class' => 'selectpicker', 
		'data-style' => 'data-style="form-control btn-default btn-outline', 'required')) !!}
	</div>
	<div class="form-group">
		{!! Form::label('status_visit','Status Visiting', array('class' => 'control-label mb-10')) !!}
		{!! Form::select('status_visit', [
				   '' => 'Select Status Visiting',
				   '1' => 'YES',
				   '0' => 'NO'], null, array('class' => 'selectpicker', 'data-style' => 'form-control btn-default btn-outline')
				) !!}
	</div>
	<div class="form-group">
        {!! Form::label('date_visit','Tanggal Visit Plan', array('class' => 'control-label mb-10')) !!}
		{!! Form::text('date_visit', date('d-F-Y H:i:s', strtotime($data['content']->date_visit)), array('class' => 'form-control', 'disabled' => 'disabled')) !!}
	</div>
	<div class="form-group">
        <div class="control-group success">
			<div class="controls">
			    {!! Form::label('date_visiting','Tanggal Visiting (Aktual)', array('class' => 'control-label mb-10')) !!}
			    <div class='input-group date' id='datetimepicker1'>
	                <input type='text' name="date_visiting" class="form-control" />
	                <span class="input-group-addon">
	                    <span class="glyphicon glyphicon-calendar"></span>
	                </span>
	            </div>
	            <span><p class="text-success mb-10">Di isi jika Status Visit "YES"</p></span>
            </div>
		</div>
	
		<div class="control-group error">
		<div class="controls">
			{!! Form::label('skip_reason','Alasan Skip Visit', array('class' => 'control-label mb-10')) !!}
			{!! Form::text('skip_reason', null, array('class' => 'form-control')) !!}
		 	<span><p class="text-info mb-10">Di isi jika Status Visit "NO"</p></span>
		</div>
	</div>

	<div class="form-group">
		{!! Form::submit($submit, array('class' => 'btn btn-primary')) !!}
	</div>
</div>

	<!-- Moment JavaScript -->
	<script type="text/javascript" src="/doodle/vendors/bower_components/moment/min/moment-with-locales.min.js"></script>
		
	<!-- Bootstrap Colorpicker JavaScript -->
	<script src="/doodle/vendors/bower_components/mjolnic-bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min.js"></script>
	<!-- Bootstrap Datetimepicker JavaScript -->
	<script type="text/javascript" src="/doodle/vendors/bower_components/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js"></script>

	<script type="text/javascript">
        $(function () {
            $('#datetimepicker1').datetimepicker({
            	format: 'YYYY-MM-DD HH:mm:ss'
            });
        });
    </script>

growth2/resources/views/pages/visitMonitor/index.blade.php
@extends('layouts.master')

@section('link', '<link rel="stylesheet" href="/doodle/vendors/bower_components/summernote/dist/summernote.css" />
    <link href="/doodle/vendors/bower_components/switchery/dist/switchery.min.css" rel="stylesheet" type="text/css"/>
    <link href="/doodle/vendors/bower_components/mjolnic-bootstrap-colorpicker/dist/css/bootstrap-colorpicker.min.css" rel="stylesheet" type="text/css"/>
  <link href="/doodle/vendors/bower_components/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css" rel="stylesheet" type="text/css"/>')

@section('title', 'Visit Monitor List')

@section('content')

        <!-- Main Content -->
        <div class="page-wrapper">
            <div class="container-fluid">
                
                <!-- Title -->
                <div class="row heading-bg">
                    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                        <h5 class="txt-dark">Visiting Monitor management</h5>
                    </div>
                    <!-- Breadcrumb -->
                    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                        <ol class="breadcrumb">
                            <li><a href="{{url('/home/dashboard')}}"><i class="fa fa-home"></i>&nbsp;Home</a></li>
                            <li><a href="#"><span>Visit Plan</span></a></li>
                            <li><a href="{{ url('/admin/visitingMonitor') }}"><span>Visiting Monitor</span></a></li>
                            <li class="active"><span>Result</span></li>
                        </ol>
                    </div>
                    <!-- /Breadcrumb -->
                </div>
                <!-- /Title -->

                <!-- Row -->
                <div class="row">
                    <div class="col-sm-12">
                        <div class="panel panel-primary card-view panel-refresh">
                            <div class="refresh-container">
                                <div class="la-anim-1"></div>
                            </div>
                            <div class="panel-heading">
                                <div class="pull-left">
                                    <h6 class="panel-title txt-light"><i class="fa fa-paper-plane"></i>&nbsp;&nbsp;Visiting Monitor</h6>
                                </div>

                                @include('partials.panel')

                                <div class="clearfix"></div>
                            </div>
                            <div id="collapse_1" class="panel-wrapper collapse in">
                                <div class="panel-body">
                                    <div class="table-wrap">

                                        <div class="table-responsive">
                                            <table class="table datable_1 table-hover table-bordered display mb-30" >
                                                <thead>
                                                    <tr>
                                                        <th style="text-align:center;">KD Visit</th>
                                                        <th style="text-align:center;">Kode Outlet</th>
                                                        <th style="text-align:center;">Sales Force</th>
                                                        <th style="text-align:center;">Nama Outlet</th>
                                                        <th style="text-align:center;">Alamat Outlet</th>
                                                        <th style="text-align:center;">Kota Outlet</th>
                                                        <th style="text-align:center;">Actual Visit</th>
                                                        <th style="text-align:center;">Status Visit</th>
                                                        <th style="text-align:center;">Skip Reason</th>
                                                        <th style="text-align:center;">Unvisited Reason</th>
                                                        @if(Auth::user()->kd_role != 3) 
                                                            <th style="text-align:center;">Action</th>
                                                        @else
                                                            <th style="text-align:center;"></th>
                                                        @endif
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    @foreach($data as $row)
                                                        <tr>
                                                            <td>{{ $row->id }}</td>
                                                            <td>{{ $row->kd_outlet }}</td>
                                                            <td>{{ $row->nama }}</td>                     
                                              
                                                            <td>{{ $row->nm_outlet }}</td>
                                                            <td>{{ $row->almt_outlet }}</td>
                                                            <td>{{ $row->nm_kota }}</td>
                                                            @if($row->date_visiting != '0000-00-00 00:00:00')
                                                                 <td>{{ date('d-F-Y H:i:s', strtotime($row->date_visiting)) }}</td>
                                                            @else
                                                                 <td> - </td>
                                                            @endif
                                                            @if($row->status_visit == 1)
                                                                <td class="center">
                                                                    <span class="label label-success">Finished</span>
                                                                </td>
                                                            @elseif($row->status_visit == 0)
                                                                @if((new DateTime($row->date_visit))->diff(new DateTime("now"))->format('%a') < 3)
                                                                    <td class="center">
                                                                        <span class="label label-warning">Waiting</span>
                                                                    </td>
                                                                @else
                                                                    <td class="center">
                                                                        <span class="label label-important">Unvisited</span>
                                                                    </td>
                                                                @endif
                                                            @else
                                                                <td class="center">
                                                                    <span class="label label-warning">Pending</span>
                                                                </td>
                                                            @endif   
                                                            <td>{{ $row->skip_reason }}</td> 
                                                            <td></td>                      
                                             
                                                            <td>
                                                                <center>
                                                                    <div class="button-list">
                                                                        <a href="{!! route('admin.visitMonitor.edit',[$row->id]) !!}" data-toggle="tooltip" title="Edit" class="btn btn-success btn-sm btn-icon-anim btn-square mr-5" style="display: unset;"><i class="fa fa-pencil" style="font-size: 10px;"></i></a>  
                                                                        <a href="{!! route('admin.visitMonitor.delete',[$row->id]) !!}" id="delete" data-toggle="tooltip" title="Delete" class="btn btn-danger btn-sm btn-icon-anim btn-square mr-5" style="display: unset;"><i class="fa fa-trash" style="font-size: 10px;"></i></a>
                                                                    </div>
                                                                </center>    
                                                            </td>
                                                        </tr>
                                                    @endforeach
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>  
                    </div>
                </div>
                <!-- /Row -->
            
                @include('partials.footer')

            </div>
        </div>
        <!-- /Main Content -->

        @include('partials.sweetalert')

        @push('message')
            @include('partials.toastr')
        @endpush

        <!-- Moment JavaScript -->
        <script type="text/javascript" src="/doodle/vendors/bower_components/moment/min/moment-with-locales.min.js"></script>
            
        <!-- Bootstrap Colorpicker JavaScript -->
        <script src="/doodle/vendors/bower_components/mjolnic-bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min.js"></script>
        <!-- Bootstrap Datetimepicker JavaScript -->
        <script type="text/javascript" src="/doodle/vendors/bower_components/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js"></script>

        <script type="text/javascript">
            $(function () {
                $('.datetimepicker1').datetimepicker({
                    format: 'YYYY-MM-DD'
                });
            });
        </script>


@endsection